name: app_restaurante
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6

  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.1.1

  # Banco de Dados
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # Utilit√°rios
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  uuid: ^4.3.3
  mask_text_input_formatter: ^2.9.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets: 
    - assets/icon.png
